### ISSUE TITLE
Why not wp_send_json() ?

### ISSUE THREAD

**Issue by franz-josef-kaiser** [Giuseppe-Mazzapica/Raph#1]
I wondered [about this](https://github.com/Giuseppe-Mazzapica/Raph/blob/master/src/Renderer.php#L40-L42) implementation.

**Comment by gmazzap** [comment]
Because [`wp_send_json`](https://developer.wordpress.org/reference/functions/wp_send_json/) **doesn't** allow to pass any additional argument to `wp_json_encode()`, but I need to pass `JSON_PRETTY_PRINT` to respect post content blank spaces.
