### ISSUE TITLE
Why not LOGGED_IN_SALT ?

### ISSUE THREAD

**Issue by franz-josef-kaiser** [Giuseppe-Mazzapica/Raph#2]
Why using a static, [accessible](https://github.com/Giuseppe-Mazzapica/Raph/blob/master/src/FormData.php#L26) and non-unique "salt" and not for e.g. `LOGGED_IN_SALT` which gets defined in `wp-config.php` anyway?

**Comment by gmazzap** [comment]
Yep, that makes sense. Actually was there for testing purpose but forgot about it. Need to be fixed.
